kind: Job
apiVersion: batch/v1
metadata:
  name: e2e
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: e2e
    spec:
      restartPolicy: Never
      containers:
        - name: e2e
          image: e2e
