---
apiVersion: v1
kind: Service
metadata:
  name: anvil-eth-sepolia
  labels:
    app: anvil-eth-sepolia
spec:
  ports:
    - port: 8545
      name: rpc
      protocol: TCP
  clusterIP: None
  selector:
    app: anvil-eth-sepolia
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: anvil-eth-sepolia
spec:
  selector:
    matchLabels:
      app: anvil-eth-sepolia
  serviceName: anvil-eth-sepolia
  replicas: 1
  template:
    metadata:
      labels:
        app: anvil-eth-sepolia
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: anvil
          image: ghcr.io/foundry-rs/foundry:v1.2.3@sha256:d9133dae61c19383b72695dc7eeca29d1e7a89f1f1b5fdfd8900c660b46b4303
          command:
            - anvil
            - --silent
            - --block-time=1
            - --host=0.0.0.0
            - --fork-url=https://ethereum-sepolia-rpc.publicnode.com
          ports:
            - containerPort: 8545
              name: rpc
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: rpc
---

